### ISSUE TITLE
Filesystem roadmap

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#379]
- [x] Remove the data folder parameter (API interface change, downstream projects affected) (#315)
 - [x] Improve API for arbitrary mounts of special real filesystem folders (API extension) (#317)
 - [x] Remove default mount of all folders (API behaviour change, downstream projects affected) (#320)
 - [ ] Replace use of PhysFS
 - [ ] Replace real filesystem methods (#212)

This is a copy of a comment that got lost in the Filesystem Update thread. This issue is for tracking those requirements:

---

New issues:
#315 Filesystem double mounting
#317 Filesystem special folders (using PhysFS) (related #212, without PhysFS)
#318 Filesystem unmount
#320 Remove Filesystem auto mounting
#321 Sort Filesystem methods into categories

Not all issues are directly on the path to replace PhysFS. In terms of replacing PhysFS, I believe the following path may work well (separate PRs):

I believe with the other steps in place first, it would simplify the last part. In particular, some of those changes help set the structure to support replacing PhysFS, such as creating methods to return special real filesystem paths, and fixing API flaws that are awkward to work with.

**Comment by cugone** [comment]
- [x] Remove the data folder parameter (API interface change, downstream projects affected) (#315)
 - [ ] Improve API for arbitrary mounts of special real filesystem folders (API extension) (#317)
 - [x] Remove default mount of all folders (API behaviour change, downstream projects affected) (#320)
 - [ ] Replace use of PhysFS
 - [ ] Replace real filesystem methods (#212)
